# Generated by Django 3.2.9 on 2021-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Mobile_no', models.CharField(max_length=10)),
                ('Company', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=30)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Last_updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
